module.exports = {
  bizName: {
    'corp': 'corp',
    'cheliang': 'cheliang',
    'cunhuo': 'cunhuo',
    'daikuan': 'daikuan',
    'danbao': 'danbao',
    'fangchan': 'fangchan',
    'fayuan': 'fayuan',
    'gerenfayuan': 'gerenfayuan',
    'gongshang': 'gongshang',
    'gongyingshang': 'gongyingshang',
    'gongzi': 'gongzi',
    'grdaikuan': 'grdaikuan',
    'grdanbao': 'grdanbao',
    'gudingzichan': 'gudingzichan',
    'gysfayuan': 'gysfayuan',
    'kehu': 'kehu',
    'lszhongbiao': 'lszhongbiao',
    'podaikuan': 'podaikuan',
    'podanbao': 'podanbao',
    'poxingyongka': 'poxingyongka',
    'qitayingfu': 'qitayingfu',
    'qitayingshou': 'qitayingshou',
    'qitaziliao': 'qitaziliao',
    'shebao': 'shebao',
    'shuiwu': 'shuiwu',
    'user': 'user',
    'xingyongka': 'xingyongka',
    'yingfu': 'yingfu',
    'yingshou': 'yingshou',
    'yonghu': 'yonghu',
    'yufu': 'yufu',
    'yushou': 'yushou',
    'zhangcheng': 'zhangcheng',
    'zizhi': 'zizhi',
  }
}
